name: liora_change_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0-252.0.dev

dependencies:
  dio: ^5.11.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  flutter_secure_storage: ^10.3.1
  go_router: ^17.3.0
  google_fonts: ^8.2.0
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
